name: Run Postman collections and generate JUnit XML reports

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-collections:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Create directory for artifacts
        run: mkdir -p SampleArtifact

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
        
      - name: Install Newman
        run: npm install -g newman newman-reporter-junitfull

      - name: Run Collection1
        run: newman run Collection1.json -r junitfull --reporter-junitfull-export output_Collection1.xml

      - name: Run Collection2
        run: newman run Collection2.json -r junitfull --reporter-junitfull-export output_Collection2.xml
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'

      # - name: Install Python dependencies
      #   run: pip install tkinter 

      - name: Run Python script
        run: |
          python compare_xml.py > SampleArtifact/comparison_output.txt
        env:
          XML_FILE1: SampleArtifact/report1.xml
          XML_FILE2: SampleArtifact/report2.xml

      - name: Publish JUnit XML Report 1
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Report 1
          path: SampleArtifact/report1.xml

      - name: Publish JUnit XML Report 2
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Report 2
          path: SampleArtifact/report2.xml
  
      - name: Publish Comparison Output
        uses: actions/upload-artifact@v4
        with:
          name: Comparison Output
          path: SampleArtifact/comparison_output.txt