name: Compare XML Reports

on:
  workflow_run:
    workflows: ["Workflow 4", "Workflow 3"]
    types:
      - completed

jobs:
  compare_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming you have a requirements.txt with dependencies

      - name: Set environment variables
        run: |
          echo "XML_FILE1=${{ github.event.workflow_run.artifacts.artifacts.JUnit Report for Collection1[0].archive_files.path }}/report1.xml" >> $GITHUB_ENV
          echo "XML_FILE2=${{ github.event.workflow_run.artifacts.artifacts.JUnit Report for Collection1[1].archive_files.path }}/report2.xml" >> $GITHUB_ENV

      - name: Run comparison script
        run: python compare_xml.py

      - name: Upload comparison output
        uses: actions/upload-artifact@v2
        with:
          name: Comparison Output
          path: SampleArtifact/comparison_output.txt
