name: Compare XML Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  compare_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Compare XML reports
        run: |
          # Fetch the commits of interest and their corresponding report files
          git fetch origin
          git checkout ${{ github.event.before }}
          cp SampleArtifact/report1.xml report1.xml
          git checkout ${{ github.sha }}
          cp SampleArtifact/report1.xml report2.xml

          # Run comparison script
          python compare_xml.py report1.xml report2.xml > SampleArtifact/comparison_output.txt

      - name: Upload comparison output
        uses: actions/upload-artifact@v2
        with:
          name: Comparison Output
          path: SampleArtifact/comparison_output.txt
