name: List SampleArtifact Directory

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    #   - name: Creating directory for artifacts
    #     run: mkdir SampleArtifact

      - name: Listing files in SampleArtifact directory
        run: ls -al SampleArtifact
