name: Workflow 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0

      - name: Installing Newman
        run: sudo npm i newman@latest

      - name: Running Postman Collection 1 and generating JUnit XML report
        run: |
          newman run "Collection1.json" -r junit --reporter-junit-export "report1.xml" || echo "Collection1 failed" >> error1.log

      - name: Configuring git for commit
        run: |
          git config --global user.name 'archisgmp'
          git config --global user.email 'archis@getmyparking.com'

      - name: Adding and committing report1.xml to the repository
        run: |
          git add report1.xml
          git commit -m "Add generated report1.xml"
          git push origin main
