name: Workflow 2

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current commit
        uses: actions/checkout@v4

      - name: Creating directory for artifacts
        run: mkdir -p SampleArtifact

      - name: Checkout the previous commit
        run: |
          git fetch --all
          git checkout HEAD~1

      - name: Copy previous Collection1.json to artifacts
        run: cp Collection1.json SampleArtifact/Collection1_previous.json

      - name: Checkout back to the current commit
        run: git checkout -

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          
      - name: Installing Newman
        run: sudo npm i newman@latest
         
      - name: Running Postman collections and generating JUnit XML reports
        run: |
          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" || echo "Collection1 failed" >> SampleArtifact/error1.log
          newman run "Collection2.json" -r junit --reporter-junit-export "SampleArtifact/report2.xml" || echo "Collection2 failed" >> SampleArtifact/error2.log

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'

      - name: Running the Python script for Collection1.json
        run: |
          python compare_xml.py > SampleArtifact/comparison_output1.txt
        env:
          XML_FILE1: SampleArtifact/Collection1_previous.json
          XML_FILE2: Collection1.json

      - name: Running the Python script for Collection2.json
        run: |
          python compare_xml.py > SampleArtifact/comparison_output2.txt
        env:
          XML_FILE1: SampleArtifact/report1.xml
          XML_FILE2: SampleArtifact/report2.xml

      - name: Publishing JUnit XML Reports
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Reports
          path: |
            SampleArtifact/report1.xml
            SampleArtifact/report2.xml

      - name: Publishing the comparison outputs
        uses: actions/upload-artifact@v4
        with:
          name: Comparison Outputs
          path: |
            SampleArtifact/comparison_output1.txt
            SampleArtifact/comparison_output2.txt

      - name: Publishing error logs (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: Error Logs
            path: SampleArtifact/error*.log

