name: Workflow 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current commit
        uses: actions/checkout@v4

      - name: Creating directory for artifacts
        run: mkdir -p SampleArtifact

      - name: Download previous report artifact
        id: download-previous-report
        uses: actions/download-artifact@v4
        with:
          name: JUnit Reports
          path: SampleArtifact
        continue-on-error: true

      - name: Check if previous report exists
        id: previous_report_check
        run: |
          if [ -f SampleArtifact/report_current.xml ]; then
            echo "previous_report_exists=true" >> $GITHUB_ENV
          else
            echo "previous_report_exists=false" >> $GITHUB_ENV
          fi

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0

      - name: Installing Newman
        run: sudo npm i newman@latest

      - name: Running current Postman collection and generating JUnit XML report
        run: |
          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report_current.xml" || echo "Collection1 failed" >> SampleArtifact/error_current.log

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Running the Python script to compare XML reports
        if: env.previous_report_exists == 'true'
        run: |
          python compare_xml.py > SampleArtifact/comparison_output.txt
        env:
          XML_FILE1: SampleArtifact/report_current.xml
          XML_FILE2: SampleArtifact/report_current.xml

      - name: Publishing JUnit XML Reports
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Reports
          path: SampleArtifact/report_current.xml

      - name: Publishing the comparison output
        if: env.previous_report_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: Comparison Output
          path: SampleArtifact/comparison_output.txt

      - name: Publishing error logs (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Error Logs
          path: SampleArtifact/error*.log
