name: Compare Artifacts from Specific Runs

on: 
   push:
    branches: [ "main" ]
   pull_request:
    branches: [ "main" ]
   workflow_dispatch:

jobs:
  compare-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step to download Artifact 1 from Workflow Run 6
    - name: Download Artifact 1
      run: |
        curl -L -o artifact1.zip "https://github.com/Repo1/actions/runs/6/artifacts/Artifact1?workflow=Workflow%203"
        unzip -q artifact1 -d artifacts/artifact1

    # Step to download Artifact 2 from Workflow Run 11
    - name: Download Artifact 2
      run: |
        curl -L -o artifact2.zip "https://github.com/Repo1/actions/runs/11/artifacts/Artifact2?workflow=Workflow%203"
        unzip -q artifact2 -d artifacts/artifact2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install xmldiff

    - name: Compare Artifacts
      run: |
        python compare_xml.py
      env:
        XML_FILE1: artifacts/artifact1/report.xml
        XML_FILE2: artifacts/artifact2/report.xml

    - name: Upload Comparison Result
      uses: actions/upload-artifact@v3
      with:
        name: comparison_result
        path: SampleArtifact/comparison_output.txt
