name: Open SampleArtifact Directory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  open-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List contents of SampleArtifact directory
        run: ls -R SampleArtifact

      - name: Zip artifacts
        run: zip -r SampleArtifact.zip SampleArtifact

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SampleArtifact Contents
          path: SampleArtifact.zip
