name: Workflow 2

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Creating directory for artifacts
        run: mkdir -p SampleArtifact

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          
      - name: Installing Newman
        run: sudo npm i newman@latest
         
      - name: Running Postman collections and generating JUnit XML reports
        run: |
          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" || echo "Collection1 failed" >> SampleArtifact/error1.log

      - name: Publishing JUnit XML Reports
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Reports
          path: |
            SampleArtifact/report1.xml

      - name: Publishing error logs (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: Error Logs
            path: SampleArtifact/error*.log
