name: Workflow 1

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Creating directory for artifacts
        run: mkdir -p SampleArtifact

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          
      - name: Installing Newman
        run: sudo npm i newman@latest
      
      - name: Checking if previous commit exists
        id: prev_commit
        run: echo "::set-output name=exists::$(git rev-parse HEAD~1 || echo 'no')"

      - name: Fetching previous commit
        if: steps.prev_commit.outputs.exists != 'no'
        run: git fetch --depth=2 && git checkout HEAD~1

      - name: Copying previous report
        if: steps.prev_commit.outputs.exists != 'no'
        run: |
          mkdir -p SampleArtifact/previous
          cp -v "SampleArtifact/report1.xml" "SampleArtifact/previous/report1.xml"
      
      - name: Checkout current commit
        if: steps.prev_commit.outputs.exists != 'no'
        run: git checkout -

      - name: Running Postman collection and generating JUnit XML report
        run: |
          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" || echo "Collection1 failed" >> SampleArtifact/error1.log
      
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.x'

      - name: Running the Python script for comparison
        if: steps.prev_commit.outputs.exists != 'no'
        run: |
          python compare_xml.py > SampleArtifact/comparison_output.txt
        env:
          XML_FILE1: SampleArtifact/previous/report1.xml
          XML_FILE2: SampleArtifact/report1.xml

      - name: Publishing JUnit XML Reports
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Reports
          path: |
            SampleArtifact/report1.xml
            SampleArtifact/previous/report1.xml

      - name: Publishing the comparison output
        if: steps.prev_commit.outputs.exists != 'no'
        uses: actions/upload-artifact@v4
        with:
          name: Comparison Output
          path: SampleArtifact/comparison_output.txt

      - name: Publishing error logs (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: Error Logs
            path: SampleArtifact/error*.log
