name: XML Comparison Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compare_xml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download existing reports
        run: |
          git fetch
          git checkout main
          mkdir -p SampleArtifact
          cp -r SampleArtifact/* .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Identify most recent XML files
        id: find_xml_files
        run: |
          ls -t SampleArtifact/*.xml | head -n 2 > xml_files.txt
          echo "::set-output name=file1::$(sed -n '1p' xml_files.txt)"
          echo "::set-output name=file2::$(sed -n '2p' xml_files.txt)"

      - name: Set environment variables for XML comparison
        run: |
          echo "XML_FILE1=$(cat xml_files.txt | head -n 1)" >> $GITHUB_ENV
          echo "XML_FILE2=$(cat xml_files.txt | tail -n 1)" >> $GITHUB_ENV

      - name: Run XML comparison script
        env:
          XML_FILE1: ${{ env.XML_FILE1 }}
          XML_FILE2: ${{ env.XML_FILE2 }}
        run: python compare_xml.py

      - name: Publish comparison result
        uses: actions/upload-artifact@v2
        with:
          name: XML Comparison Result
          path: SampleArtifact/comparison_output.txt
