name: Compare XML Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_before:
        description: 'SHA of the commit before the current one'
        required: true
        default: '3d6fe4105dda28d4c5f03734424a95ce4be3f32c'
      current_commit:
        description: 'SHA of the current commit'
        required: true
        default: 'bee73f83acc400e69c6aff3e280e6a09ab8a7708'

jobs:
  compare_reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assuming requirements.txt lists dependencies for compare_xml.py

      - name: Compare XML reports
        run: |
          # Fetch the commits of interest and their corresponding report files
          git fetch origin
          git checkout ${{ github.event.inputs.commit_before }}
          cp SampleArtifact/report1.xml report1.xml
          git checkout ${{ github.event.inputs.current_commit }}
          cp SampleArtifact/report1.xml report2.xml

          # Run comparison script
          python compare_xml.py report1.xml report2.xml > SampleArtifact/comparison_output.txt

      - name: Upload comparison output
        uses: actions/upload-artifact@v2
        with:
          name: Comparison Output
          path: SampleArtifact/comparison_output.txt
