name: Workflow 2

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Creating directory for artifacts
        run: mkdir -p SampleArtifact

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
          
      - name: Installing Newman
        run: sudo npm i newman@latest
         
      - name: Running Postman Collection 1 and generating JUnit XML report
        run: |
          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report-${{ github.sha }}.xml" || echo "Collection1 failed" >> SampleArtifact/error-${{ github.sha }}.log

      - name: Publishing JUnit XML Report
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Report for Commit ${{ github.sha }}
          path: SampleArtifact/report-${{ github.sha }}.xml

      - name: Publishing error log (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Error Log for Commit ${{ github.sha }}
          path: SampleArtifact/error-${{ github.sha }}.log
