name: XML Comparison Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  compare_xml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Assuming you already have a job or step that generates XML reports.
      
      - name: Download existing reports
        run: |
          git fetch
          git checkout main
          mkdir -p SampleArtifact
          cp -r SampleArtifact/* .

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Installing required Python packages
        run: pip install lxml

      - name: Set environment variables for XML comparison
        run: |
          echo "XML_FILE1=SampleArtifact/report_$(ls -t SampleArtifact | grep '^report_' | tail -n 2 | head -n 1)" >> $GITHUB_ENV
          echo "XML_FILE2=SampleArtifact/report_$(ls -t SampleArtifact | grep '^report_' | head -n 1)" >> $GITHUB_ENV

      - name: Running XML comparison script
        run: python compare_xml.py

      - name: Publishing comparison result
        uses: actions/upload-artifact@v4
        with:
          name: XML Comparison Result
          path: SampleArtifact/comparison_output.txt

